version: 2.1
orbs:
  aws-cli: circleci/aws-cli@x.y

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: aws --version

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
